# postgres
postgresql:
  image: postgres:9.5
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: docker
    POSTGRES_PASSWORD: docker
    POSTGRES_DB: docker

# golang
golang:
  build: ../../golang
  volumes:
    - "${ROOT_DIR}/src/go:/go/src/app"
    - "${ROOT_DIR}/www:/var/www"
  links:
    - postgresql:db
  working_dir: /go/src/app

# nginx
nginx:
  build: ../../nginx
  volumes:
    - "${ROOT_DIR}/www:/var/www"
    - "${ROOT_DIR}/conf/golang_nginx.conf:/etc/nginx/sites-enabled/default"
  links:
    - golang
  ports:
    - "80:80"
